version: '3'

dotenv: ['.env']

tasks:
  install:
    cmds:
      - docker run --name postgres_course -p 5432:5432 -e POSTGRES_PASSWORD=$PG_PASS -d postgres
  tune:
    cmds:
      - docker cp settings.sql  postgres_course:/
      - docker exec -it postgres_course  sh -c "psql -U postgres < settings.sql"
      - docker restart postgres_course
  thai:copy:
    cmds:
      - docker cp $DUMP_PATH postgres_course:/
  thai:install:
    cmds:
      - docker exec -it postgres_course  sh -c "psql -U postgres < thai.sql"
  replicas:up:
    cmds:
      - docker compose up
  replicas:tune:
    cmds:
      - docker compose cp settings.sql  master:/
      - docker compose exec -it master  sh -c "psql -U postgres < settings.sql"
      - docker compose restart master
      - docker compose cp settings.sql  replica_1:/
      - docker compose exec -it replica_1  sh -c "psql -U postgres < settings.sql"
      - docker compose restart replica_1
  replicas:down:
    cmds:
      - docker compose down