version: '3'

dotenv: ['.env']

tasks:
  install:
    cmds:
      - docker run --name postgres_course -p 5432:5432 -e POSTGRES_PASSWORD=$PG_PASS -d postgres
  tune:
    cmds:
      - docker cp settings.sql  postgres_course:/
      - docker exec -it postgres_course  sh -c "psql -U postgres < settings.sql"
      - docker restart postgres_course
  thai:copy:
    cmds:
      - docker cp $DUMP_PATH postgres_course:/
  thai:install:
    cmds:
      - docker exec -it postgres_course  sh -c "psql -U postgres < thai.sql"
  replicas:up:
    cmds:
      - docker compose up
  replicas:install:schema:
    deps: [ replicas:master:install:schema, replicas:replica:one:install:schema ]
  replicas:create:pubsub:
    cmds:
      - docker compose exec -it master  sh -c 'psql -U postgres -c "CREATE DATABASE thai"'
      - docker compose exec -it master  sh -c 'psql -U postgres -c "ALTER SYSTEM SET wal_level = logical"'
      - docker compose cp settings.sql  master:/
      - docker compose exec -it master  sh -c "psql -U postgres < settings.sql"
      - docker compose restart master
      - docker compose exec -it master  sh -c 'psql -U postgres -d thai -c "CREATE PUBLICATION thai_pub FOR ALL TABLES"'
      - docker compose exec -it replica_1  sh -c 'psql -U postgres -c "CREATE DATABASE thai"'
      - docker compose exec -it replica_1 sh -c 'psql -U postgres -c "ALTER SYSTEM SET wal_level = logical"'
      - docker compose cp settings.sql  replica_1:/
      - docker compose exec -it replica_1  sh -c "psql -U postgres < settings.sql"
      - docker compose restart replica_1
      - docker compose cp $BACKUP_PATH  replica_1:/thaidump
      - docker compose exec -it replica_1  sh -c "pg_restore -U postgres -s -v -F d -j 6 -d thai thaidump"
      - docker compose exec -it replica_1 sh -c "psql -U postgres -d thai -c \"CREATE SUBSCRIPTION thai_sub CONNECTION 'host=master port=5432 user=postgres dbname=thai' PUBLICATION thai_pub\""
  replicas:master:install:
    cmds:
      - time docker compose cp $BACKUP_PATH  master:/thaidump
      - time docker compose exec -it master  sh -c "pg_restore -U postgres -v -F d -j 6 -d thai thaidump"
  replicas:down:
    cmds:
      - docker compose down -v
  replicas:all:
    deps:
      - task: replicas:tune
      - task: replicas:install:schema
      - task: replicas:master:public
      - task: replicas:replica:one:subscribe